<!DOCTYPE html>
<html lang="pt-PT">
<head>
    <meta charset="UTF-8">

    <style>
        @page {
            margin: 32px;
        }

        body {
            font-family: DejaVu Sans, sans-serif;
            color: #111827;
            font-size: 12px;
            line-height: 1.65;
            background: #ffffff;
        }

        .cover {
            padding: 28px;
            background: #0B0D17;
            color: #E8EAF0;
            border-radius: 12px;
            margin-bottom: 28px;
        }

        .brand {
            font-size: 13px;
            color: #A855F7;
            font-weight: bold;
            margin-bottom: 10px;
            text-transform: uppercase;
            letter-spacing: 1px;
        }

        .cover h1 {
            font-size: 28px;
            margin: 0 0 10px;
            color: #ffffff;
        }

        .cover p {
            margin: 0;
            color: #cbd5e1;
        }

        h1 {
            font-size: 24px;
            color: #0B0D17;
            margin-top: 26px;
            margin-bottom: 12px;
        }

        h2 {
            font-size: 17px;
            color: #111827;
            margin-top: 24px;
            margin-bottom: 10px;
            padding-bottom: 6px;
            border-bottom: 2px solid #A855F7;
        }

        h3 {
            font-size: 14px;
            color: #1f2937;
            margin-top: 18px;
            margin-bottom: 8px;
        }

        p {
            margin: 0 0 10px;
        }

        ul, ol {
            margin-top: 6px;
            margin-bottom: 12px;
            padding-left: 22px;
        }

        li {
            margin-bottom: 4px;
        }

        code {
            background: #f3e8ff;
            color: #6d28d9;
            padding: 2px 5px;
            border-radius: 4px;
            font-size: 11px;
        }

        pre {
            background: #0B0D17;
            color: #E8EAF0;
            padding: 12px;
            border-radius: 8px;
            overflow: hidden;
            white-space: pre-wrap;
            font-size: 10px;
            line-height: 1.45;
            margin: 12px 0;
        }

        pre code {
            background: transparent;
            color: #E8EAF0;
            padding: 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin: 14px 0;
        }

        th {
            background: #121525;
            color: #E8EAF0;
            text-align: left;
        }

        th, td {
            border: 1px solid #e5e7eb;
            padding: 8px;
            font-size: 11px;
        }

        blockquote {
            border-left: 4px solid #7C3AED;
            margin: 12px 0;
            padding: 8px 12px;
            background: #f8fafc;
            color: #475569;
        }

        .footer {
            margin-top: 32px;
            padding-top: 12px;
            border-top: 1px solid #e5e7eb;
            color: #6b7280;
            font-size: 10px;
        }
    </style>
</head>
<body>

    <div class="cover">
        <div class="brand">BackendAI Documentation</div>
        <h1>{{ $project->name }}</h1>
        <p>Documentação técnica gerada automaticamente pela plataforma BackendAI.</p>
    </div>

    <main>
        {!! $htmlContent !!}
    </main>

    <div class="footer">
        Generated by BackendAI · {{ now()->format('d/m/Y H:i') }}
    </div>

</body>
</html>
