<?php

namespace App\Services\Documentation;

use App\Models\Project;
use Illuminate\Support\Str;

class ProjectDocumentationGenerator
{
    /**
     * Gera documentação Markdown para um projeto BackendAI.
     *
     * A documentação usa os dados já guardados no projeto:
     * - nome
     * - descrição
     * - framework
     * - specification
     * - endpoints
     */
    public function generate(Project $project): string
    {
        // Carregar relações necessárias para evitar queries repetidas.
        $project->load(['specification', 'endpoints']);

        $spec = $project->specification?->spec ?? [];

        $projectName = $project->name;
        $framework = ucfirst($project->framework ?? 'Laravel');
        $description = $project->description ?? 'No description provided.';
        $authEnabled = ($spec['auth']['enabled'] ?? false) === true;
        $entities = $spec['entities'] ?? [];

        return $this->buildMarkdown(
            projectName: $projectName,
            framework: $framework,
            description: $description,
            authEnabled: $authEnabled,
            entities: $entities,
            endpoints: $project->endpoints
        );
    }

    /**
     * Monta o conteúdo final em Markdown.
     */
    protected function buildMarkdown(
        string $projectName,
        string $framework,
        string $description,
        bool $authEnabled,
        array $entities,
        $endpoints
    ): string {
        $entitiesSection   = $this->buildEntitiesSection($entities);
        $endpointsSection  = $this->buildEndpointsSection($endpoints);
        $controllersSection = $this->buildControllersSection($entities);
        $authText = $authEnabled
            ? 'This project includes authentication endpoints and protected routes.'
            : 'This project does not include authentication by default.';

        $bt = '```';

        return "# {$projectName}\n\n"
            . "## 1. Project Overview\n\n"
            . "{$description}\n\n"
            . "## 2. Framework\n\n"
            . "This backend was generated using **{$framework}**.\n\n"
            . "## 3. Installation\n\n"
            . "To install the project dependencies, run:\n\n"
            . "{$bt}bash\n"
            . "composer install\n"
            . "{$bt}\n\n"
            . "Then create the environment file:\n\n"
            . "{$bt}bash\n"
            . "cp .env.example .env\n"
            . "{$bt}\n\n"
            . "Generate the application key:\n\n"
            . "{$bt}bash\n"
            . "php artisan key:generate\n"
            . "{$bt}\n\n"
            . "## 4. Database Setup\n\n"
            . "Configure your database connection in the `.env` file.\n\n"
            . "Example:\n\n"
            . "{$bt}env\n"
            . "DB_CONNECTION=pgsql\n"
            . "DB_HOST=127.0.0.1\n"
            . "DB_PORT=5432\n"
            . "DB_DATABASE=your_database\n"
            . "DB_USERNAME=your_username\n"
            . "DB_PASSWORD=your_password\n"
            . "{$bt}\n\n"
            . "After configuring the database, run:\n\n"
            . "{$bt}bash\n"
            . "php artisan migrate\n"
            . "{$bt}\n\n"
            . "## 5. Running the Server\n\n"
            . "Start the Laravel development server:\n\n"
            . "{$bt}bash\n"
            . "php artisan serve\n"
            . "{$bt}\n\n"
            . "By default, the application will run at:\n\n"
            . "{$bt}\n"
            . "http://127.0.0.1:8000\n"
            . "{$bt}\n\n"
            . "## 6. Authentication\n\n"
            . "{$authText}\n\n"
            . "## 7. Main Entities\n\n"
            . "{$entitiesSection}\n\n"
            . "## 8. API Endpoints\n\n"
            . "{$endpointsSection}\n\n"
            . "## 9. Controllers\n\n"
            . "{$controllersSection}\n\n"
            . "## 10. Testing with BackendAI API Tester\n\n"
            . "To test this backend using the BackendAI API Tester:\n\n"
            . "1. Open the generated backend project.\n"
            . "2. Install dependencies with `composer install`.\n"
            . "3. Configure the `.env` file.\n"
            . "4. Run migrations with `php artisan migrate`.\n"
            . "5. Start the server with a custom port, for example:\n\n"
            . "{$bt}bash\n"
            . "php artisan serve --port=9000\n"
            . "{$bt}\n\n"
            . "6. Go back to BackendAI.\n"
            . "7. Open the API Tester section.\n"
            . "8. Select this project.\n"
            . "9. Use the Base URL:\n\n"
            . "{$bt}\n"
            . "http://127.0.0.1:9000\n"
            . "{$bt}\n\n"
            . "10. Select an endpoint and click **Send Request**.\n\n"
            . "## 11. Notes\n\n"
            . "This documentation was automatically generated by BackendAI based on the project specification and generated endpoints.\n";
    }

    /**
     * Gera a secção das entidades/modelos.
     */
    protected function buildEntitiesSection(array $entities): string
    {
        if (empty($entities)) {
            return 'No entities were detected.';
        }

        return collect($entities)
            ->map(function ($entity) {
                $name   = $entity['name'] ?? 'UnknownEntity';
                $table  = $entity['table'] ?? Str::snake(Str::pluralStudly($name));
                $fields = $entity['fields'] ?? [];

                $fieldsText = collect($fields)
                    ->map(function ($field) {
                        $fieldName = $field['name']     ?? 'unknown';
                        $fieldType = $field['type']     ?? 'string';
                        $required  = ($field['required'] ?? false) ? 'required' : 'optional';

                        return "- `{$fieldName}` ({$fieldType}, {$required})";
                    })
                    ->implode("\n");

                return "### {$name}\n\n"
                    . "Database table: `{$table}`\n\n"
                    . "Fields:\n\n"
                    . "{$fieldsText}";
            })
            ->implode("\n\n");
    }

    /**
     * Gera a secção dos endpoints.
     */
    protected function buildEndpointsSection($endpoints): string
    {
        if ($endpoints->isEmpty()) {
            return 'No endpoints were generated for this project.';
        }

        $bt = '```';

        return $endpoints
            ->map(function ($endpoint) use ($bt) {
                $auth = $endpoint->requires_auth ? 'Yes' : 'No';
                $body = $endpoint->sample_body
                    ? json_encode($endpoint->sample_body, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE)
                    : null;

                $bodySection = $body
                    ? "\nExample body:\n\n{$bt}json\n{$body}\n{$bt}"
                    : '';

                return "### {$endpoint->method} `{$endpoint->path}`\n\n"
                    . "- **Name:** {$endpoint->name}\n"
                    . "- **Description:** {$endpoint->description}\n"
                    . "- **Requires authentication:** {$auth}"
                    . $bodySection;
            })
            ->implode("\n\n");
    }

    /**
     * Gera uma explicação simples dos controllers esperados.
     */
    protected function buildControllersSection(array $entities): string
    {
        if (empty($entities)) {
            return 'No controllers were detected.';
        }

        return collect($entities)
            ->filter(fn ($entity) => ($entity['name'] ?? null) !== 'User')
            ->map(function ($entity) {
                $name = $entity['name'] ?? 'Unknown';

                return "### {$name}Controller\n\n"
                    . "Responsible for handling HTTP requests related to the `{$name}` entity.\n\n"
                    . "Main responsibilities:\n\n"
                    . "- List records\n"
                    . "- Show a single record\n"
                    . "- Create new records\n"
                    . "- Update existing records\n"
                    . "- Delete records";
            })
            ->implode("\n\n");
    }
}
